IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'VENDA')
BEGIN
    CREATE TABLE VENDA (
        ID INTEGER PRIMARY KEY NOT NULL,
        DATA DATETIME,
        ID_VENDEDOR INTEGER,
        VALOR_VENDA NUMERIC(12,3) NOT NULL,
        VALOR_DESCONTO NUMERIC(12,3) NOT NULL,
        VALOR_TOTAL NUMERIC(12,3) NOT NULL
    );
END;