IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'VENDA')
BEGIN
INSERT INTO venda (ID, DATA, ID_VENDEDOR, VALOR_VENDA, VALOR_DESCONTO, VALOR_TOTAL)
SELECT 
    CONVERT(INTEGER, [Id da Venda]), 
    CONVERT(DATETIME, data), 
    CONVERT(INTEGER, [vendedor]), 
    CONVERT(NUMERIC(12,3), [valor da venda]), 
    CONVERT(NUMERIC(12,3), [Valor do Desconto]), 
    CONVERT(NUMERIC(12,3), [Valor Total])
FROM vendas;
END;